# Generated by Django 3.2.3 on 2021-09-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='partipants',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.Participant'),
        ),
    ]
