# Generated by Django 3.2.3 on 2021-09-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_partipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2021-04-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_model',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
